//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeIdentityApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDep_Mapping
    {
        public int MapId { get; set; }
        public Nullable<int> DepId { get; set; }
        public Nullable<int> EmpId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Department Department { get; set; }
    }
}
